-- TASK 1
SELECT 
  STD_CHILD.ID AS REPORT_CARD_NUMBER, 
  STD_CHILD.SURNAME, 
  STD_CHILD.NAME, 
  STD_CHILD.PATRONYMIC,
  
  STD_PAYER.SURNAME AS PAYER_SURNAME, 
  STD_PAYER.NAME AS PAYER_NAME, 
  STD_PAYER.PATRONYMIC AS PAYER_PATRONYMIC,
  
  STD_GROUP.NAME AS GROUP_NAME,
  
  STD_GROUP_TYPE.NAME AS GROUP_TYPE,
  
  STD_GENERAL_MONTH.BALANCE,
  STD_GENERAL_MONTH.EXEMPTION,
  STD_GENERAL_MONTH.PRICE

FROM STD_CHILD
INNER JOIN STD_PAYER_AND_CHILD ON STD_PAYER_AND_CHILD.CHILD_ID = STD_CHILD.ID
INNER JOIN STD_PAYER ON STD_PAYER_AND_CHILD.PAYER_ID = STD_PAYER.ID
INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_CHILD.ID
INNER JOIN STD_GROUP ON STD_CHILD_AND_GROUP.GROUP_ID = STD_GROUP.ID
INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_GROUP.ID
INNER JOIN STD_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_GROUP_TYPE.ID
LEFT JOIN STD_GENERAL_MONTH ON STD_GENERAL_MONTH.CHILD_ID = STD_CHILD.ID
WHERE 
  TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_PAYER_AND_CHILD.BEGIN AND NVL(STD_PAYER_AND_CHILD.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
  TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
  TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
  TO_DATE('09-2023', 'MM-YYYY') = STD_GENERAL_MONTH.MONTH
ORDER BY REPORT_CARD_NUMBER;
