-- TASK 2
SELECT 
  STD_GROUP.NAME,
  STD_CHILD.SURNAME, 
  STD_CHILD.NAME, 
  STD_CHILD.PATRONYMIC
FROM STD_CHILD
INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_CHILD.ID
INNER JOIN STD_GROUP ON STD_CHILD_AND_GROUP.GROUP_ID = STD_GROUP.ID
WHERE TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
ORDER BY STD_GROUP.NAME; 
