-- TASK 3
SELECT 
   STD_GROUP.NAME,
   
   STD_GROUP_TYPE.NAME,
   
   STD_RATE.PRICE_DAY
FROM STD_GROUP
INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_GROUP.ID
INNER JOIN STD_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_GROUP_TYPE.ID
INNER JOIN STD_RATE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_RATE.GROUP_TYPE_ID
WHERE TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
      TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_RATE.BEGIN AND NVL(STD_RATE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
ORDER BY STD_GROUP.NAME;  
