-- TASK 4
SELECT 
  REPORT_CARD_NUMBER,
  SURNAME, 
  NAME, 
  PATRONYMIC,
    
  "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
  "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
  "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", 
  "31",
      
  COUNT_VISITED
FROM
(
  SELECT 
    STD_DAY.CHILD_ID AS REPORT_CARD_NUMBER,
    STD_CHILD.SURNAME, 
    STD_CHILD.NAME, 
    STD_CHILD.PATRONYMIC,
       
    TO_CHAR(STD_DAY.DAY_DATE, 'DD') AS DAY_NUMBER,
      
    STD_DAY_TYPE.TYPE AS DAY_TYPE

  FROM STD_CHILD
  INNER JOIN STD_DAY ON STD_DAY.CHILD_ID = STD_CHILD.ID
  INNER JOIN STD_DAY_TYPE ON STD_DAY.DAY_TYPE_ID = STD_DAY_TYPE.ID
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_CHILD.ID
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND 
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND 
        STD_CHILD_AND_GROUP.GROUP_ID = 2
    
  UNION
    
  SELECT 
    999999999 AS CHILD_ID,
    NULL AS SURNAME, 
    NULL AS NAME, 
    CAST('¬—≈√Œ œŒ “¿¡≈Àﬁ' AS NVARCHAR2(30))  AS PATRONYMIC,
       
    TO_CHAR(STD_DAY.DAY_DATE, 'DD') AS DAY_NUMBER,
      
    CAST(COUNT(STD_DAY.DAY_DATE) AS NVARCHAR2(5)) AS DAY_TYPE

  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  WHERE STD_DAY.DAY_TYPE_ID = 1 AND STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND 
        STD_CHILD_AND_GROUP.GROUP_ID = 2
  GROUP BY STD_DAY.DAY_DATE
)
PIVOT
(
  MAX(DAY_TYPE)
  FOR DAY_NUMBER 
  IN 
  (
    '01' AS "01",'02' AS "02",'03' AS "03",'04' AS "04",'05' AS "05",'06' AS "06",'07' AS "07",'08' AS "08",'09' AS "09",'10' AS "10",
    '11' AS "11",'12' AS "12",'13' AS "13",'14' AS "14",'15' AS "15",'16' AS "16",'17' AS "17",'18' AS "18",'19' AS "19",'20' AS "20",
    '21' AS "21",'22' AS "22",'23' AS "23",'24' AS "24",'25' AS "25",'26' AS "26",'27' AS "27",'28' AS "28",'29' AS "29",'30' AS "30",
    '31' AS "31"
  )
)
INNER JOIN 
( 
  SELECT
    STD_DAY.CHILD_ID AS REPORT_CARD,
    COUNT(STD_DAY.DAY_DATE) AS COUNT_VISITED
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  WHERE STD_DAY.DAY_TYPE_ID = 1 AND STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND 
        STD_CHILD_AND_GROUP.GROUP_ID = 2
  GROUP BY
    STD_DAY.CHILD_ID
      
  UNION
    
  SELECT
    999999999 AS CHILD_ID,
    COUNT(STD_DAY.DAY_DATE) AS COUNT_VISITED
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  WHERE STD_DAY.DAY_TYPE_ID = 1 AND STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND 
        STD_CHILD_AND_GROUP.GROUP_ID = 2
      
) STD_COUNT_VISITED ON STD_COUNT_VISITED.REPORT_CARD = REPORT_CARD_NUMBER

ORDER BY 
  SURNAME,
  NAME,
  PATRONYMIC 
