-- TASK 5
SELECT 
  NAME,
  GROUP_TYPE,
  COUNT_CHILDREN,
  
  "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
  "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
  "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", 
  "31",
  
  COUNT_VISITED
FROM
(
  SELECT   
    STD_GROUP.ID AS GROUP_ID,
    STD_GROUP.NAME,
    STD_GROUP_TYPE.NAME AS GROUP_TYPE,
    TO_CHAR(STD_DAY.DAY_DATE, 'DD') AS DAY_NUMBER,
    COUNT(STD_DAY.DAY_DATE) AS DAY_DATE
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  INNER JOIN STD_GROUP ON STD_CHILD_AND_GROUP.GROUP_ID = STD_GROUP.ID
  INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_GROUP.ID
  INNER JOIN STD_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_GROUP_TYPE.ID
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_DATE BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_TYPE_ID = 1
  GROUP BY
    STD_GROUP.ID,
    STD_GROUP.NAME,
    STD_GROUP_TYPE.NAME,
    STD_DAY.DAY_DATE
        
  UNION
  
  -- GROUP_TYPE
  SELECT 
    STD_GROUP_TYPE.ID+1000 AS GROUP_ID,
    CAST('хрнц' AS NVARCHAR2(30)) AS NAME,
    STD_GROUP_TYPE.NAME AS GROUP_TYPE,
    TO_CHAR(STD_DAY.DAY_DATE, 'DD') AS DAY_NUMBER,
    COUNT(STD_DAY.DAY_DATE) AS DAY_DATE
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_CHILD_AND_GROUP.GROUP_ID
  INNER JOIN STD_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_GROUP_TYPE.ID
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_DATE BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_TYPE_ID = 1
  GROUP BY
    STD_GROUP_TYPE.ID,
    STD_GROUP_TYPE.NAME,
    STD_DAY.DAY_DATE
  
  UNION
  
  -- ALL
  SELECT 
    999999999 AS GROUP_ID,
    CAST('хрнц' AS NVARCHAR2(30)) AS NAME,
    CAST('бяе цпсоош' AS NVARCHAR2(30)) AS GROUP_TYPE,
    TO_CHAR(STD_DAY.DAY_DATE, 'DD') AS DAY_NUMBER,
    COUNT(STD_DAY.DAY_DATE) AS DAY_DATE
  FROM STD_DAY
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_TYPE_ID = 1
  GROUP BY
    STD_DAY.DAY_DATE
)
PIVOT
(
  MAX(DAY_DATE)
  FOR DAY_NUMBER 
  IN 
  (
    '01' AS "01",'02' AS "02",'03' AS "03",'04' AS "04",'05' AS "05",'06' AS "06",'07' AS "07",'08' AS "08",'09' AS "09",'10' AS "10",
    '11' AS "11",'12' AS "12",'13' AS "13",'14' AS "14",'15' AS "15",'16' AS "16",'17' AS "17",'18' AS "18",'19' AS "19",'20' AS "20",
    '21' AS "21",'22' AS "22",'23' AS "23",'24' AS "24",'25' AS "25",'26' AS "26",'27' AS "27",'28' AS "28",'29' AS "29",'30' AS "30",
    '31' AS "31"
  )
) STD_PIVOT
-- VISITED
LEFT JOIN
(
  SELECT 
    STD_CHILD_AND_GROUP.GROUP_ID,
    COUNT(STD_DAY.DAY_DATE) AS COUNT_VISITED
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_TYPE_ID = 1
  GROUP BY
    STD_CHILD_AND_GROUP.GROUP_ID
    
  UNION 
  
  -- GROUP_TYPE
  SELECT 
    STD_GROUP_TYPE.ID+1000 AS GROUP_ID,
    COUNT(STD_DAY.DAY_DATE) AS COUNT_VISITED
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_CHILD_AND_GROUP.GROUP_ID
  INNER JOIN STD_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_GROUP_TYPE.ID
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_DATE BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_TYPE_ID = 1  
  GROUP BY
    STD_GROUP_TYPE.ID
  
  UNION 
    
  -- ALL
  SELECT 
    999999999 AS GROUP_ID,
    COUNT(STD_DAY.DAY_DATE) AS COUNT_VISITED
  FROM STD_DAY
  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND TO_DATE('01-10-2023', 'DD-MM-YYYY') AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_TYPE_ID = 1

) STD_COUNT_VISITED ON STD_COUNT_VISITED.GROUP_ID = STD_PIVOT.GROUP_ID
-- CHILDREN
INNER JOIN 
(
  SELECT
    STD_CHILD_AND_GROUP.GROUP_ID,
    COUNT(STD_CHILD_AND_GROUP.CHILD_ID) AS COUNT_CHILDREN
  FROM STD_CHILD_AND_GROUP
  WHERE TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
  GROUP BY
    STD_CHILD_AND_GROUP.GROUP_ID
  
  UNION
  
  -- GROUP_TYPE
  SELECT
    STD_GROUP_TYPE.ID+1000 AS GROUP_ID,
    COUNT(STD_CHILD_AND_GROUP.CHILD_ID) AS COUNT_CHILDREN
  FROM STD_CHILD_AND_GROUP
  INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_CHILD_AND_GROUP.GROUP_ID
  INNER JOIN STD_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID = STD_GROUP_TYPE.ID
  WHERE TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        TO_DATE('01-09-2023', 'DD-MM-YYYY')BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
  GROUP BY
    STD_GROUP_TYPE.ID
  
  UNION
  
  -- ALL
  SELECT
    999999999 AS GROUP_ID,
    COUNT(STD_CHILD_AND_GROUP.CHILD_ID) AS COUNT_CHILDREN
  FROM STD_CHILD_AND_GROUP
  WHERE TO_DATE('01-09-2023', 'DD-MM-YYYY') BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))

) STD_COUNT_CHILDREN ON STD_COUNT_CHILDREN.GROUP_ID = STD_PIVOT.GROUP_ID

ORDER BY 
  GROUP_TYPE DESC,
  NAME ASC
