CREATE OR REPLACE PROCEDURE STD_CANCULATE_PRICE(month IN DATE) IS
  first_day_current_month DATE;
  first_day_next_month DATE;
BEGIN
  first_day_current_month := TRUNC(month, 'MM');
  first_day_next_month := ADD_MONTHS(first_day_current_month, 1);

  INSERT INTO STD_GENERAL_MONTH(CHILD_ID,PRICE,EXEMPTION,COUNT, MONTH)
  SELECT
    CHILD_ID,
    PRICE_DAY * (1 - DISCOUNT) AS PRICE,
    DISCOUNT,
    COUNT(PRICE_DAY) AS COUNT,
    first_day_current_month AS MONTH
  FROM
  (
    SELECT
      STD_DAY.DAY_DATE,
      STD_CHILD.ID AS CHILD_ID,
      STD_CHILD.SURNAME,
      STD_CHILD.NAME,
      STD_CHILD.PATRONYMIC,
        
      STD_RATE.PRICE_DAY,

      NVL(SUM(STD_EXEMPTION.DISCOUNT),0) AS DISCOUNT
    FROM STD_DAY
    INNER JOIN STD_CHILD ON STD_DAY.CHILD_ID = STD_CHILD.ID

    LEFT JOIN 
        STD_EXEMPTION_AND_CHILD ON STD_EXEMPTION_AND_CHILD.CHILD_ID = STD_DAY.CHILD_ID 
        AND STD_DAY.DAY_DATE BETWEEN NVL(STD_EXEMPTION_AND_CHILD.BEGIN, TO_DATE('01-01-2000', 'DD-MM-YYYY')) 
        AND NVL(STD_EXEMPTION_AND_CHILD.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
    LEFT JOIN STD_EXEMPTION ON STD_EXEMPTION_AND_CHILD.EXEMPTION_ID = STD_EXEMPTION.ID

    INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
    INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_CHILD_AND_GROUP.GROUP_ID
    INNER JOIN STD_RATE ON STD_RATE.GROUP_TYPE_ID =  STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID

    WHERE STD_DAY.DAY_DATE BETWEEN first_day_current_month AND first_day_next_month AND
          STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
          STD_DAY.DAY_DATE BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
          STD_DAY.DAY_DATE BETWEEN STD_RATE.BEGIN AND NVL(STD_RATE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
          
    GROUP BY
      STD_DAY.DAY_DATE,
      STD_CHILD.ID,
      STD_CHILD.SURNAME,
      STD_CHILD.NAME,
      STD_CHILD.PATRONYMIC,
        
      STD_RATE.PRICE_DAY
         
    ORDER BY STD_DAY.DAY_DATE
  )
  GROUP BY 
    CHILD_ID,
    DISCOUNT,
    PRICE_DAY;
END STD_CANCULATE_PRICE;
/
