SELECT
  SURNAME,
  NAME,
  PATRONYMIC,
  DISCOUNT,
  PRICE_DAY * (1 - DISCOUNT) AS PRICE_DAY,
  COUNT(PRICE_DAY) AS COUNT
FROM
(
  SELECT
    STD_DAY.DAY_DATE,
    STD_CHILD.SURNAME,
    STD_CHILD.NAME,
    STD_CHILD.PATRONYMIC,
    
    STD_RATE.PRICE_DAY,

    NVL(SUM(STD_EXEMPTION.DISCOUNT),0) AS DISCOUNT
  FROM STD_DAY
  INNER JOIN STD_CHILD ON STD_DAY.CHILD_ID = STD_CHILD.ID

  LEFT JOIN 
      STD_EXEMPTION_AND_CHILD ON STD_EXEMPTION_AND_CHILD.CHILD_ID = STD_DAY.CHILD_ID 
      AND STD_DAY.DAY_DATE BETWEEN NVL(STD_EXEMPTION_AND_CHILD.BEGIN, TO_DATE('01-01-2000', 'DD-MM-YYYY')) 
      AND NVL(STD_EXEMPTION_AND_CHILD.END, TO_DATE('31-12-9999', 'DD-MM-YYYY'))
  LEFT JOIN STD_EXEMPTION ON STD_EXEMPTION_AND_CHILD.EXEMPTION_ID = STD_EXEMPTION.ID

  INNER JOIN STD_CHILD_AND_GROUP ON STD_CHILD_AND_GROUP.CHILD_ID = STD_DAY.CHILD_ID
  INNER JOIN STD_GROUP_AND_GROUP_TYPE ON STD_GROUP_AND_GROUP_TYPE.GROUP_ID = STD_CHILD_AND_GROUP.GROUP_ID
  INNER JOIN STD_RATE ON STD_RATE.GROUP_TYPE_ID =  STD_GROUP_AND_GROUP_TYPE.GROUP_TYPE_ID

  WHERE STD_DAY.DAY_DATE BETWEEN TO_DATE('01-09-2023', 'DD-MM-YYYY') AND NVL(TO_DATE('01-10-2023', 'DD-MM-YYYY'), TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_DATE BETWEEN STD_CHILD_AND_GROUP.BEGIN AND NVL(STD_CHILD_AND_GROUP.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_DATE BETWEEN STD_GROUP_AND_GROUP_TYPE.BEGIN AND NVL(STD_GROUP_AND_GROUP_TYPE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        STD_DAY.DAY_DATE BETWEEN STD_RATE.BEGIN AND NVL(STD_RATE.END, TO_DATE('31-12-9999', 'DD-MM-YYYY')) AND
        
        STD_CHILD.ID = 3
  GROUP BY
    STD_DAY.DAY_DATE,
    STD_CHILD.SURNAME,
    STD_CHILD.NAME,
    STD_CHILD.PATRONYMIC,
    
    STD_RATE.PRICE_DAY
     
  ORDER BY STD_DAY.DAY_DATE
)
GROUP BY 
  SURNAME,
  NAME,
  PATRONYMIC,
  DISCOUNT,
  PRICE_DAY
    
ORDER BY 
  SURNAME,
  NAME,
  PATRONYMIC
